CREATE TABLE IF NOT EXISTS "visit_events" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country" varchar(2) NOT NULL DEFAULT 'ZZ',
  "path" varchar(160) NOT NULL DEFAULT '/',
  "referrer_host" varchar(255),
  "visited_at" timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "visit_events_visited_at_idx" ON "visit_events" ("visited_at");
CREATE INDEX IF NOT EXISTS "visit_events_country_idx" ON "visit_events" ("country");
--> statement-breakpoint
