ALTER TABLE "contact_messages" ADD COLUMN IF NOT EXISTS "is_spam" boolean NOT NULL DEFAULT false;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "blocked_contact_ips" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ip_address" varchar(128) NOT NULL UNIQUE,
  "note" varchar(255),
  "blocked_at" timestamp NOT NULL DEFAULT NOW()
);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS "contact_rate_limits" (
  "ip_address" varchar(128) PRIMARY KEY,
  "window_started_at" timestamp NOT NULL DEFAULT NOW(),
  "message_count" integer NOT NULL DEFAULT 0,
  "updated_at" timestamp NOT NULL DEFAULT NOW()
);
--> statement-breakpoint

CREATE INDEX IF NOT EXISTS "blocked_contact_ips_blocked_at_idx" ON "blocked_contact_ips" ("blocked_at");
CREATE INDEX IF NOT EXISTS "contact_rate_limits_updated_at_idx" ON "contact_rate_limits" ("updated_at");
