CREATE TABLE IF NOT EXISTS "admin_change_logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "scope" varchar(100) NOT NULL,
  "entity_type" varchar(100) NOT NULL,
  "entity_id" varchar(100),
  "action" varchar(40) NOT NULL,
  "summary" varchar(255) NOT NULL,
  "before_state" jsonb,
  "after_state" jsonb,
  "created_at" timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "admin_change_logs_created_at_idx" ON "admin_change_logs" ("created_at");
