-- Database-backed Academic Foundation content.
CREATE TABLE IF NOT EXISTS academic_foundation_categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(120) NOT NULL UNIQUE,
  description text,
  order_index integer NOT NULL DEFAULT 0,
  is_visible boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS academic_foundation_courses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id integer NOT NULL REFERENCES academic_foundation_categories(id),
  name varchar(255) NOT NULL,
  short_description text,
  related_project varchar(255),
  related_project_id integer,
  order_index integer NOT NULL DEFAULT 0,
  is_featured boolean NOT NULL DEFAULT false,
  is_visible boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS academic_foundation_courses_category_idx
  ON academic_foundation_courses (category_id);
CREATE INDEX IF NOT EXISTS academic_foundation_courses_order_idx
  ON academic_foundation_courses (order_index);

DO $$
DECLARE
  software_id integer;
  algorithms_id integer;
  ai_id integer;
  systems_id integer;
  mathematics_id integer;
  business_id integer;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM academic_foundation_categories LIMIT 1) THEN
    INSERT INTO academic_foundation_categories (name, description, order_index)
    VALUES
      ('Software Engineering & Product Development', 'Building reliable software from object-oriented foundations to complete products.', 0),
      ('Algorithms & Computer Science', 'Core computational thinking, data structures, algorithms, and formal reasoning.', 1),
      ('AI & Machine Learning', 'Academic foundations behind intelligent systems, pattern recognition, and neural models.', 2),
      ('Systems & Computing', 'Low-level computing, digital logic, architecture, and mobile systems foundations.', 3),
      ('Mathematics', 'Mathematical tools that support analytical thinking and machine learning.', 4),
      ('Business & Supporting Studies', 'Supporting coursework connecting technology with communication, business, and creative systems.', 5);

    SELECT id INTO software_id FROM academic_foundation_categories WHERE name = 'Software Engineering & Product Development';
    SELECT id INTO algorithms_id FROM academic_foundation_categories WHERE name = 'Algorithms & Computer Science';
    SELECT id INTO ai_id FROM academic_foundation_categories WHERE name = 'AI & Machine Learning';
    SELECT id INTO systems_id FROM academic_foundation_categories WHERE name = 'Systems & Computing';
    SELECT id INTO mathematics_id FROM academic_foundation_categories WHERE name = 'Mathematics';
    SELECT id INTO business_id FROM academic_foundation_categories WHERE name = 'Business & Supporting Studies';

    INSERT INTO academic_foundation_courses (category_id, name, short_description, related_project, order_index, is_featured)
    VALUES
      (software_id, 'Object-Oriented Programming I', 'Object-oriented programming fundamentals and structured software design.', 'Full-stack portfolio platform', 0, true),
      (software_id, 'Object-Oriented Programming II', 'Advanced object-oriented design, reuse, and maintainable application structure.', 'Full-stack portfolio platform', 1, true),
      (software_id, 'Software Development I', 'Software development practices, requirements, and implementation fundamentals.', 'Hirelay', 2, true),
      (software_id, 'Software Development II', 'Applied software engineering workflows and collaborative product development.', 'Swadeshi', 3, true),
      (software_id, 'Software Development III', 'Advanced software development, integration, and delivery practices.', 'Neighbour', 4, true),
      (software_id, 'Database Management System', 'Relational data modeling, queries, persistence, and data integrity.', 'Portfolio CMS and visitor analytics', 5, true),
      (software_id, 'System Designing', 'Designing modular software systems and planning production-ready architecture.', 'Multi-agent AI OS', 6, true),
      (software_id, 'Mobile Computing', 'Mobile application concepts, constraints, and connected computing environments.', null, 7, false),
      (algorithms_id, 'Data Structures', 'Organizing data for efficient storage, access, and transformation.', 'AI matching and analytics', 0, true),
      (algorithms_id, 'Algorithms', 'Algorithmic problem solving, complexity, and optimization foundations.', 'Search and workflow logic', 1, true),
      (algorithms_id, 'Theory of Computation', 'Formal models of computation, languages, and computational limits.', null, 2, false),
      (ai_id, 'Artificial Intelligence and Expert System', 'Knowledge representation, reasoning, and intelligent decision systems.', 'Xervis and intelligent automation', 0, true),
      (ai_id, 'Pattern Recognition', 'Recognizing meaningful patterns in structured and unstructured data.', 'SentimentScope', 1, true),
      (ai_id, 'Neural Network', 'Neural computation, learning concepts, and model-based pattern analysis.', 'Machine learning experiments', 2, true),
      (ai_id, 'Statistics', 'Probability and statistical reasoning for analysis and machine learning.', 'Analytics and evaluation', 3, true),
      (systems_id, 'Microprocessor and Assembly Language', 'Processor-level programming and low-level system behavior.', 'Arduino-based Military Radar System', 0, false),
      (systems_id, 'Digital Logic Design', 'Logic gates, digital circuits, and the foundations of computer hardware.', 'Arduino and embedded systems', 1, false),
      (systems_id, 'Multimedia and Graphics System', 'Digital media, graphics concepts, and visual computing systems.', null, 2, false),
      (mathematics_id, 'Differential Calculus', 'Rates of change and mathematical tools used in analytical modeling.', null, 0, false),
      (mathematics_id, 'Mathematical Analysis', 'Rigorous mathematical reasoning and analytical foundations.', null, 1, false),
      (business_id, 'Financial and Managerial Accounting', 'Business fundamentals for understanding financial and operational decisions.', null, 0, false),
      (business_id, 'Industrial Management', 'Organizational, operational, and management principles in industry.', null, 1, false);
  END IF;
END $$;
