-- CV preview and download analytics. Raw IP visibility is restricted to authenticated admins.
CREATE TABLE IF NOT EXISTS cv_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind varchar(24) NOT NULL,
  source varchar(40) NOT NULL DEFAULT 'unknown',
  path varchar(160) NOT NULL DEFAULT '/#cv',
  referrer_host varchar(255),
  ip_address varchar(128) NOT NULL,
  country varchar(2) NOT NULL DEFAULT 'ZZ',
  device_type varchar(32),
  browser varchar(64),
  operating_system varchar(64),
  user_agent varchar(500),
  visitor_hash varchar(64),
  deleted_at timestamp,
  created_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS cv_events_kind_created_at_idx
  ON cv_events (kind, created_at);
CREATE INDEX IF NOT EXISTS cv_events_created_at_idx
  ON cv_events (created_at);
CREATE INDEX IF NOT EXISTS cv_events_visitor_hash_idx
  ON cv_events (visitor_hash);

ALTER TABLE cv_events
  ADD CONSTRAINT cv_events_kind_check
  CHECK (kind IN ('cv_preview', 'cv_download'));

ALTER TABLE cv_events
  ADD CONSTRAINT cv_events_source_check
  CHECK (source IN ('hero', 'cv-section', 'direct', 'unknown'));
