import { sql } from "drizzle-orm";
import { getDb } from "../queries/connection";

let ensurePromise: Promise<void> | null = null;

export function ensureAcademicFoundationTables() {
  if (!ensurePromise) {
    ensurePromise = (async () => {
      const db = getDb();
      await db.execute(sql`CREATE TABLE IF NOT EXISTS "academic_foundation_categories" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" varchar(120) NOT NULL UNIQUE,
        "description" text,
        "order_index" integer NOT NULL DEFAULT 0,
        "is_visible" boolean NOT NULL DEFAULT true,
        "created_at" timestamp NOT NULL DEFAULT now(),
        "updated_at" timestamp NOT NULL DEFAULT now()
      )`);
      await db.execute(sql`CREATE TABLE IF NOT EXISTS "academic_foundation_courses" (
        "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "category_id" integer NOT NULL REFERENCES "academic_foundation_categories"("id"),
        "name" varchar(255) NOT NULL,
        "short_description" text,
        "related_project" varchar(255),
        "related_project_id" integer,
        "order_index" integer NOT NULL DEFAULT 0,
        "is_featured" boolean NOT NULL DEFAULT false,
        "is_visible" boolean NOT NULL DEFAULT true,
        "created_at" timestamp NOT NULL DEFAULT now(),
        "updated_at" timestamp NOT NULL DEFAULT now()
      )`);
      await db.execute(sql`CREATE INDEX IF NOT EXISTS "academic_foundation_courses_category_idx" ON "academic_foundation_courses" ("category_id")`);
      await db.execute(sql`CREATE INDEX IF NOT EXISTS "academic_foundation_courses_order_idx" ON "academic_foundation_courses" ("order_index")`);
      await db.execute(sql`INSERT INTO "academic_foundation_categories" ("name", "description", "order_index")
        VALUES
          ('Software Engineering & Product Development', 'Building reliable software from object-oriented foundations to complete products.', 0),
          ('Algorithms & Computer Science', 'Core computational thinking, data structures, algorithms, and formal reasoning.', 1),
          ('AI & Machine Learning', 'Academic foundations behind intelligent systems, pattern recognition, and neural models.', 2),
          ('Systems & Computing', 'Low-level computing, digital logic, architecture, and mobile systems foundations.', 3),
          ('Mathematics', 'Mathematical tools that support analytical thinking and machine learning.', 4),
          ('Business & Supporting Studies', 'Supporting coursework connecting technology with communication, business, and creative systems.', 5)
        ON CONFLICT ("name") DO NOTHING`);
      await db.execute(sql`INSERT INTO "academic_foundation_courses" ("category_id", "name", "short_description", "related_project", "order_index", "is_featured")
        SELECT categories."id", seed."name", seed."short_description", seed."related_project", seed."order_index", seed."is_featured"
        FROM (VALUES
          ('Software Engineering & Product Development', 'Object-Oriented Programming I', 'Object-oriented programming fundamentals and structured software design.', 'Full-stack portfolio platform', 0, true),
          ('Software Engineering & Product Development', 'Object-Oriented Programming II', 'Advanced object-oriented design, reuse, and maintainable application structure.', 'Full-stack portfolio platform', 1, true),
          ('Software Engineering & Product Development', 'Software Development I', 'Software development practices, requirements, and implementation fundamentals.', 'Hirelay', 2, true),
          ('Software Engineering & Product Development', 'Software Development II', 'Applied software engineering workflows and collaborative product development.', 'Swadeshi', 3, true),
          ('Software Engineering & Product Development', 'Software Development III', 'Advanced software development, integration, and delivery practices.', 'Neighbour', 4, true),
          ('Software Engineering & Product Development', 'Database Management System', 'Relational data modeling, queries, persistence, and data integrity.', 'Portfolio CMS and visitor analytics', 5, true),
          ('Software Engineering & Product Development', 'System Designing', 'Designing modular software systems and planning production-ready architecture.', 'Multi-agent AI OS', 6, true),
          ('Software Engineering & Product Development', 'Mobile Computing', 'Mobile application concepts, constraints, and connected computing environments.', NULL, 7, false),
          ('Algorithms & Computer Science', 'Data Structures', 'Organizing data for efficient storage, access, and transformation.', 'AI matching and analytics', 0, true),
          ('Algorithms & Computer Science', 'Algorithms', 'Algorithmic problem solving, complexity, and optimization foundations.', 'Search and workflow logic', 1, true),
          ('Algorithms & Computer Science', 'Theory of Computation', 'Formal models of computation, languages, and computational limits.', NULL, 2, false),
          ('AI & Machine Learning', 'Artificial Intelligence and Expert System', 'Knowledge representation, reasoning, and intelligent decision systems.', 'Xervis and intelligent automation', 0, true),
          ('AI & Machine Learning', 'Pattern Recognition', 'Recognizing meaningful patterns in structured and unstructured data.', 'SentimentScope', 1, true),
          ('AI & Machine Learning', 'Neural Network', 'Neural computation, learning concepts, and model-based pattern analysis.', 'Machine learning experiments', 2, true),
          ('AI & Machine Learning', 'Statistics', 'Probability and statistical reasoning for analysis and machine learning.', 'Analytics and evaluation', 3, true),
          ('Systems & Computing', 'Microprocessor and Assembly Language', 'Processor-level programming and low-level system behavior.', 'Arduino-based Military Radar System', 0, false),
          ('Systems & Computing', 'Digital Logic Design', 'Logic gates, digital circuits, and the foundations of computer hardware.', 'Arduino and embedded systems', 1, false),
          ('Systems & Computing', 'Multimedia and Graphics System', 'Digital media, graphics concepts, and visual computing systems.', NULL, 2, false),
          ('Mathematics', 'Differential Calculus', 'Rates of change and mathematical tools used in analytical modeling.', NULL, 0, false),
          ('Mathematics', 'Mathematical Analysis', 'Rigorous mathematical reasoning and analytical foundations.', NULL, 1, false),
          ('Business & Supporting Studies', 'Financial and Managerial Accounting', 'Business fundamentals for understanding financial and operational decisions.', NULL, 0, false),
          ('Business & Supporting Studies', 'Industrial Management', 'Organizational, operational, and management principles in industry.', NULL, 1, false)
        ) AS seed("category_name", "name", "short_description", "related_project", "order_index", "is_featured")
        JOIN "academic_foundation_categories" categories ON categories."name" = seed."category_name"
        WHERE NOT EXISTS (SELECT 1 FROM "academic_foundation_courses")`);
    })();
  }
  return ensurePromise;
}
