import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { and, desc, eq, gte, ilike, isNotNull, isNull, lt, lte, or, sql } from "drizzle-orm";
import { createRouter, publicQuery } from "../middleware";
import { createAdminRouter, adminProcedure } from "./admin-middleware";
import { getDb } from "../queries/connection";
import { visitEvents } from "@db/schema";

const ipActivity = new Map<string, { windowStart: number; count: number; alerted: boolean }>();
const EVENT_WINDOW_MS = 5 * 60 * 1000;
const EVENT_THROTTLE_MS = 15 * 60 * 1000;
const SUSPICIOUS_REQUEST_LIMIT = 30;
const RETENTION_DAYS = 365;

const visitorFilterSchema = z.object({
  days: z.number().int().min(1).max(365).default(30),
  country: z.string().trim().regex(/^[A-Z]{2}$/).optional(),
  search: z.string().trim().max(160).optional(),
  startDate: z.string().datetime({ offset: true }).optional(),
  endDate: z.string().datetime({ offset: true }).optional(),
});

type VisitorFilterInput = z.infer<typeof visitorFilterSchema>;

function buildVisitorFilters(input: VisitorFilterInput) {
  const start = input.startDate ? new Date(input.startDate) : new Date(Date.now() - input.days * 24 * 60 * 60 * 1000);
  const end = input.endDate ? new Date(input.endDate) : undefined;
  if (end && start > end) {
    throw new TRPCError({ code: "BAD_REQUEST", message: "The visitor date range is invalid." });
  }
  const search = input.search?.trim();
  const searchFilter = search
    ? or(
        ilike(visitEvents.ipAddress, `%${search}%`),
        ilike(visitEvents.country, `%${search.toUpperCase()}%`),
        ilike(visitEvents.path, `%${search}%`),
        ilike(visitEvents.referrerHost, `%${search}%`),
        ilike(visitEvents.userAgent, `%${search}%`),
      )
    : undefined;
  return and(
    isNull(visitEvents.deletedAt),
    gte(visitEvents.visitedAt, start),
    end ? lte(visitEvents.visitedAt, end) : undefined,
    input.country ? eq(visitEvents.country, input.country) : undefined,
    searchFilter,
  );
}

function normalizeCountry(value: string | null) {
  const country = value?.trim().toUpperCase() || "ZZ";
  return /^[A-Z]{2}$/.test(country) ? country : "ZZ";
}

function getCountry(req: Request) {
  return normalizeCountry(req.headers.get("cf-ipcountry") || req.headers.get("x-country-code") || req.headers.get("x-vercel-ip-country") || req.headers.get("x-geo-country"));
}

function getClientIp(req: Request) {
  const raw = req.headers.get("cf-connecting-ip") || req.headers.get("x-real-ip") || req.headers.get("x-forwarded-for")?.split(",")[0] || "unknown";
  return raw.trim().replace(/[^-a-zA-Z0-9:._%]/g, "").slice(0, 128) || "unknown";
}

function getReferrerHost(req: Request) {
  const value = req.headers.get("referer");
  if (!value) return null;
  try { return new URL(value).hostname.slice(0, 255); } catch { return null; }
}

function getUserAgent(req: Request) {
  return (req.headers.get("user-agent") || "unknown").slice(0, 500);
}

export async function ensureVisitEventsTable() {
  try {
    const db = getDb();
    await db.execute(sql`CREATE TABLE IF NOT EXISTS "visit_events" ("id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "ip_address" varchar(128), "country" varchar(2) NOT NULL DEFAULT 'ZZ', "path" varchar(160) NOT NULL DEFAULT '/', "referrer_host" varchar(255), "user_agent" varchar(500), "is_suspicious" boolean NOT NULL DEFAULT false, "visited_at" timestamp NOT NULL DEFAULT now())`);
    await db.execute(sql`ALTER TABLE "visit_events" ADD COLUMN IF NOT EXISTS "ip_address" varchar(128)`);
    await db.execute(sql`ALTER TABLE "visit_events" ADD COLUMN IF NOT EXISTS "user_agent" varchar(500)`);
    await db.execute(sql`ALTER TABLE "visit_events" ADD COLUMN IF NOT EXISTS "is_suspicious" boolean NOT NULL DEFAULT false`);
    await db.execute(sql`ALTER TABLE "visit_events" ADD COLUMN IF NOT EXISTS "deleted_at" timestamp`);
    await db.execute(sql`UPDATE "visit_events" SET "ip_address" = 'unknown' WHERE "ip_address" IS NULL`);
    await db.execute(sql`ALTER TABLE "visit_events" ALTER COLUMN "ip_address" SET NOT NULL`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS "visit_events_visited_at_idx" ON "visit_events" ("visited_at")`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS "visit_events_ip_address_idx" ON "visit_events" ("ip_address")`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS "visit_events_country_idx" ON "visit_events" ("country")`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS "visit_events_deleted_at_idx" ON "visit_events" ("deleted_at")`);
  } catch (error) {
    console.error('[analytics] schema guard failed', error);
  }
}

export const analyticsRouter = createRouter({
  track: publicQuery.input(z.object({ path: z.string().trim().min(1).max(160).default("/") })).mutation(async ({ input, ctx }) => {
    const ipAddress = getClientIp(ctx.req);
    const now = Date.now();
    const activity = ipActivity.get(ipAddress);
    const current = !activity || now - activity.windowStart >= EVENT_WINDOW_MS
      ? { windowStart: now, count: 1, alerted: false }
      : { ...activity, count: activity.count + 1 };
    ipActivity.set(ipAddress, current);
    const isSuspicious = current.count >= SUSPICIOUS_REQUEST_LIMIT;
    const shouldRecordVisit = !activity || now - activity.windowStart >= EVENT_THROTTLE_MS;
    const shouldRecordAlert = isSuspicious && !current.alerted;
    if (!shouldRecordVisit && !shouldRecordAlert) return { recorded: false, suspicious: isSuspicious };
    if (shouldRecordAlert) current.alerted = true;

    await getDb().insert(visitEvents).values({
      ipAddress,
      country: getCountry(ctx.req),
      path: input.path,
      referrerHost: getReferrerHost(ctx.req),
      userAgent: getUserAgent(ctx.req),
      isSuspicious,
    });
    return { recorded: shouldRecordVisit, suspicious: isSuspicious };
  }),
});

export const analyticsAdminRouter = createAdminRouter({
  summary: adminProcedure.input(z.object({ days: z.number().int().min(1).max(365).default(30) }).optional()).query(async ({ input }) => {
    const db = getDb();
    const days = input?.days || 30;
    const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
    const retentionCutoff = new Date(Date.now() - RETENTION_DAYS * 24 * 60 * 60 * 1000);
    await db.delete(visitEvents).where(lt(visitEvents.visitedAt, retentionCutoff));
    const range = gte(visitEvents.visitedAt, since);
    const [totals] = await db.select({ total: sql<number>`count(*)`, uniqueIps: sql<number>`count(distinct ${visitEvents.ipAddress})` }).from(visitEvents).where(range);
    const [alerts] = await db.select({ total: sql<number>`count(*)` }).from(visitEvents).where(and(range, eq(visitEvents.isSuspicious, true)));
    const countries = await db.select({ country: visitEvents.country, visits: sql<number>`count(*)` }).from(visitEvents).where(range).groupBy(visitEvents.country).orderBy(desc(sql`count(*)`));
    const paths = await db.select({ path: visitEvents.path, visits: sql<number>`count(*)` }).from(visitEvents).where(range).groupBy(visitEvents.path).orderBy(desc(sql`count(*)`)).limit(20);
    const ips = await db.select({
      ipAddress: visitEvents.ipAddress,
      country: sql<string>`(array_agg(${visitEvents.country} order by ${visitEvents.visitedAt} desc))[1]`,
      visits: sql<number>`count(*)`,
      suspicious: sql<number>`sum(case when ${visitEvents.isSuspicious} then 1 else 0 end)`,
      lastSeen: sql<Date>`max(${visitEvents.visitedAt})`,
    }).from(visitEvents).where(range).groupBy(visitEvents.ipAddress).orderBy(desc(sql`count(*)`));
    const daily = await db.select({ day: sql<string>`to_char(date_trunc('day', ${visitEvents.visitedAt}), 'YYYY-MM-DD')`, visits: sql<number>`count(*)` }).from(visitEvents).where(range).groupBy(sql`date_trunc('day', ${visitEvents.visitedAt})`).orderBy(sql`date_trunc('day', ${visitEvents.visitedAt})`);
    return {
      periodDays: days,
      totalVisits: Number(totals?.total || 0),
      uniqueIps: Number(totals?.uniqueIps || 0),
      suspiciousEvents: Number(alerts?.total || 0),
      countries: countries.map((row) => ({ country: row.country, visits: Number(row.visits) })),
      topPaths: paths.map((row) => ({ path: row.path, visits: Number(row.visits) })),
      topIps: ips.map((row) => ({ ipAddress: row.ipAddress, country: row.country, visits: Number(row.visits), suspicious: Number(row.suspicious || 0), lastSeen: row.lastSeen })),
      daily: daily.map((row) => ({ day: row.day, visits: Number(row.visits) })),
    };
  }),

  events: adminProcedure
    .input(visitorFilterSchema.extend({
      page: z.number().int().min(1).max(10000).default(1),
      pageSize: z.number().int().min(10).max(100).default(25),
    }))
    .query(async ({ input }) => {
      const db = getDb();
      const filters = buildVisitorFilters(input);
      const offset = (input.page - 1) * input.pageSize;
      const [countRow] = await db.select({ total: sql<number>`count(*)` }).from(visitEvents).where(filters);
      const rows = await db.select({
        id: visitEvents.id,
        ipAddress: visitEvents.ipAddress,
        country: visitEvents.country,
        path: visitEvents.path,
        referrerHost: visitEvents.referrerHost,
        userAgent: visitEvents.userAgent,
        suspicious: visitEvents.isSuspicious,
        visitedAt: visitEvents.visitedAt,
      }).from(visitEvents).where(filters).orderBy(desc(visitEvents.visitedAt)).limit(input.pageSize).offset(offset);
      const daily = await db.select({
        day: sql<string>`to_char(date_trunc('day', ${visitEvents.visitedAt}), 'YYYY-MM-DD')`,
        visits: sql<number>`count(*)`,
      }).from(visitEvents).where(filters).groupBy(sql`date_trunc('day', ${visitEvents.visitedAt})`).orderBy(sql`date_trunc('day', ${visitEvents.visitedAt})`);
      const total = Number(countRow?.total || 0);
      return {
        page: input.page,
        pageSize: input.pageSize,
        total,
        totalPages: Math.max(1, Math.ceil(total / input.pageSize)),
        events: rows,
        daily: daily.map((row) => ({ day: row.day, visits: Number(row.visits) })),
      };
    }),

  deleteFiltered: adminProcedure
    .input(visitorFilterSchema)
    .mutation(async ({ input }) => {
      const db = getDb();
      const filters = buildVisitorFilters(input);
      const now = new Date();
      const deleted = await db.update(visitEvents).set({ deletedAt: now }).where(filters).returning({ id: visitEvents.id });
      return { deletedCount: deleted.length };
    }),

  recycleBin: adminProcedure.query(async () => {
    const db = getDb();
    return db.select({
      id: visitEvents.id,
      ipAddress: visitEvents.ipAddress,
      country: visitEvents.country,
      path: visitEvents.path,
      visitedAt: visitEvents.visitedAt,
      deletedAt: visitEvents.deletedAt,
    }).from(visitEvents).where(isNotNull(visitEvents.deletedAt)).orderBy(desc(visitEvents.deletedAt)).limit(100);
  }),

  restore: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => {
    const db = getDb();
    await db.update(visitEvents).set({ deletedAt: null }).where(and(eq(visitEvents.id, input.id), isNotNull(visitEvents.deletedAt)));
    return { success: true };
  }),

  permanentlyDelete: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => {
    const db = getDb();
    const deleted = await db.delete(visitEvents).where(and(eq(visitEvents.id, input.id), isNotNull(visitEvents.deletedAt))).returning({ id: visitEvents.id });
    return { success: deleted.length > 0 };
  }),
});
