import { z } from "zod";
import { desc, gte, sql } from "drizzle-orm";
import { createRouter, publicQuery } from "../middleware";
import { createAdminRouter, adminProcedure } from "./admin-middleware";
import { getDb } from "../queries/connection";
import { visitEvents } from "@db/schema";

const recentEventByIp = new Map<string, number>();
const EVENT_THROTTLE_MS = 15 * 60 * 1000;

function normalizeCountry(value: string | null) {
  const country = value?.trim().toUpperCase() || "ZZ";
  return /^[A-Z]{2}$/.test(country) ? country : "ZZ";
}

function getCountry(req: Request) {
  return normalizeCountry(req.headers.get("cf-ipcountry") || req.headers.get("x-country-code") || req.headers.get("x-vercel-ip-country") || req.headers.get("x-geo-country"));
}

function getClientKey(req: Request) {
  return req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || req.headers.get("x-real-ip") || req.headers.get("cf-connecting-ip") || "unknown";
}

function getReferrerHost(req: Request) {
  const value = req.headers.get("referer");
  if (!value) return null;
  try { return new URL(value).hostname.slice(0, 255); } catch { return null; }
}

export async function ensureVisitEventsTable() {
  try {
    const db = getDb();
    await db.execute(sql`CREATE TABLE IF NOT EXISTS "visit_events" ("id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "country" varchar(2) NOT NULL DEFAULT 'ZZ', "path" varchar(160) NOT NULL DEFAULT '/', "referrer_host" varchar(255), "visited_at" timestamp NOT NULL DEFAULT now())`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS "visit_events_visited_at_idx" ON "visit_events" ("visited_at")`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS "visit_events_country_idx" ON "visit_events" ("country")`);
  } catch (error) {
    console.error('[analytics] schema guard failed', error);
  }
}

export const analyticsRouter = createRouter({
  track: publicQuery.input(z.object({ path: z.string().trim().min(1).max(160).default("/") })).mutation(async ({ input, ctx }) => {
    const clientKey = getClientKey(ctx.req);
    const now = Date.now();
    const lastSeen = recentEventByIp.get(clientKey);
    if (lastSeen && now - lastSeen < EVENT_THROTTLE_MS) return { recorded: false };
    recentEventByIp.set(clientKey, now);
    await getDb().insert(visitEvents).values({ country: getCountry(ctx.req), path: input.path, referrerHost: getReferrerHost(ctx.req) });
    return { recorded: true };
  }),
});

export const analyticsAdminRouter = createAdminRouter({
  summary: adminProcedure.query(async () => {
    const db = getDb();
    const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
    const [totals] = await db.select({ total: sql<number>`count(*)` }).from(visitEvents).where(gte(visitEvents.visitedAt, since));
    const countries = await db.select({ country: visitEvents.country, visits: sql<number>`count(*)` }).from(visitEvents).where(gte(visitEvents.visitedAt, since)).groupBy(visitEvents.country).orderBy(desc(sql`count(*)`));
    const paths = await db.select({ path: visitEvents.path, visits: sql<number>`count(*)` }).from(visitEvents).where(gte(visitEvents.visitedAt, since)).groupBy(visitEvents.path).orderBy(desc(sql`count(*)`)).limit(10);
    return { periodDays: 30, totalVisits: Number(totals?.total || 0), countries: countries.map((row) => ({ country: row.country, visits: Number(row.visits) })), topPaths: paths.map((row) => ({ path: row.path, visits: Number(row.visits) })) };
  }),
});
