import { z } from "zod";
import { and, desc, eq, gte, lt, sql } from "drizzle-orm";
import { createRouter, publicQuery } from "../middleware";
import { createAdminRouter, adminProcedure } from "./admin-middleware";
import { getDb } from "../queries/connection";
import { visitEvents } from "@db/schema";

const ipActivity = new Map<string, { windowStart: number; count: number; alerted: boolean }>();
const EVENT_WINDOW_MS = 5 * 60 * 1000;
const EVENT_THROTTLE_MS = 15 * 60 * 1000;
const SUSPICIOUS_REQUEST_LIMIT = 30;
const RETENTION_DAYS = 365;

function normalizeCountry(value: string | null) {
  const country = value?.trim().toUpperCase() || "ZZ";
  return /^[A-Z]{2}$/.test(country) ? country : "ZZ";
}

function getCountry(req: Request) {
  return normalizeCountry(req.headers.get("cf-ipcountry") || req.headers.get("x-country-code") || req.headers.get("x-vercel-ip-country") || req.headers.get("x-geo-country"));
}

function getClientIp(req: Request) {
  const raw = req.headers.get("cf-connecting-ip") || req.headers.get("x-real-ip") || req.headers.get("x-forwarded-for")?.split(",")[0] || "unknown";
  return raw.trim().replace(/[^a-zA-Z0-9:.%_\-]/g, "").slice(0, 128) || "unknown";
}

function getReferrerHost(req: Request) {
  const value = req.headers.get("referer");
  if (!value) return null;
  try { return new URL(value).hostname.slice(0, 255); } catch { return null; }
}

function getUserAgent(req: Request) {
  return (req.headers.get("user-agent") || "unknown").slice(0, 500);
}

export async function ensureVisitEventsTable() {
  try {
    const db = getDb();
    await db.execute(sql`CREATE TABLE IF NOT EXISTS "visit_events" ("id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "ip_address" varchar(128), "country" varchar(2) NOT NULL DEFAULT 'ZZ', "path" varchar(160) NOT NULL DEFAULT '/', "referrer_host" varchar(255), "user_agent" varchar(500), "is_suspicious" boolean NOT NULL DEFAULT false, "visited_at" timestamp NOT NULL DEFAULT now())`);
    await db.execute(sql`ALTER TABLE "visit_events" ADD COLUMN IF NOT EXISTS "ip_address" varchar(128)`);
    await db.execute(sql`ALTER TABLE "visit_events" ADD COLUMN IF NOT EXISTS "user_agent" varchar(500)`);
    await db.execute(sql`ALTER TABLE "visit_events" ADD COLUMN IF NOT EXISTS "is_suspicious" boolean NOT NULL DEFAULT false`);
    await db.execute(sql`UPDATE "visit_events" SET "ip_address" = 'unknown' WHERE "ip_address" IS NULL`);
    await db.execute(sql`ALTER TABLE "visit_events" ALTER COLUMN "ip_address" SET NOT NULL`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS "visit_events_visited_at_idx" ON "visit_events" ("visited_at")`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS "visit_events_ip_address_idx" ON "visit_events" ("ip_address")`);
    await db.execute(sql`CREATE INDEX IF NOT EXISTS "visit_events_country_idx" ON "visit_events" ("country")`);
  } catch (error) {
    console.error('[analytics] schema guard failed', error);
  }
}

export const analyticsRouter = createRouter({
  track: publicQuery.input(z.object({ path: z.string().trim().min(1).max(160).default("/") })).mutation(async ({ input, ctx }) => {
    const ipAddress = getClientIp(ctx.req);
    const now = Date.now();
    const activity = ipActivity.get(ipAddress);
    const current = !activity || now - activity.windowStart >= EVENT_WINDOW_MS
      ? { windowStart: now, count: 1, alerted: false }
      : { ...activity, count: activity.count + 1 };
    ipActivity.set(ipAddress, current);
    const isSuspicious = current.count >= SUSPICIOUS_REQUEST_LIMIT;
    const shouldRecordVisit = !activity || now - activity.windowStart >= EVENT_THROTTLE_MS;
    const shouldRecordAlert = isSuspicious && !current.alerted;
    if (!shouldRecordVisit && !shouldRecordAlert) return { recorded: false, suspicious: isSuspicious };
    if (shouldRecordAlert) current.alerted = true;

    await getDb().insert(visitEvents).values({
      ipAddress,
      country: getCountry(ctx.req),
      path: input.path,
      referrerHost: getReferrerHost(ctx.req),
      userAgent: getUserAgent(ctx.req),
      isSuspicious,
    });
    return { recorded: shouldRecordVisit, suspicious: isSuspicious };
  }),
});

export const analyticsAdminRouter = createAdminRouter({
  summary: adminProcedure.input(z.object({ days: z.number().int().min(1).max(365).default(30) }).optional()).query(async ({ input }) => {
    const db = getDb();
    const days = input?.days || 30;
    const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000);
    const retentionCutoff = new Date(Date.now() - RETENTION_DAYS * 24 * 60 * 60 * 1000);
    await db.delete(visitEvents).where(lt(visitEvents.visitedAt, retentionCutoff));
    const range = gte(visitEvents.visitedAt, since);
    const [totals] = await db.select({ total: sql<number>`count(*)`, uniqueIps: sql<number>`count(distinct ${visitEvents.ipAddress})` }).from(visitEvents).where(range);
    const [alerts] = await db.select({ total: sql<number>`count(*)` }).from(visitEvents).where(and(range, eq(visitEvents.isSuspicious, true)));
    const countries = await db.select({ country: visitEvents.country, visits: sql<number>`count(*)` }).from(visitEvents).where(range).groupBy(visitEvents.country).orderBy(desc(sql`count(*)`));
    const paths = await db.select({ path: visitEvents.path, visits: sql<number>`count(*)` }).from(visitEvents).where(range).groupBy(visitEvents.path).orderBy(desc(sql`count(*)`)).limit(20);
    const ips = await db.select({ ipAddress: visitEvents.ipAddress, country: visitEvents.country, visits: sql<number>`count(*)`, suspicious: sql<number>`sum(case when ${visitEvents.isSuspicious} then 1 else 0 end)` }).from(visitEvents).where(range).groupBy(visitEvents.ipAddress, visitEvents.country).orderBy(desc(sql`count(*)`)).limit(50);
    const daily = await db.select({ day: sql<string>`to_char(date_trunc('day', ${visitEvents.visitedAt}), 'YYYY-MM-DD')`, visits: sql<number>`count(*)` }).from(visitEvents).where(range).groupBy(sql`date_trunc('day', ${visitEvents.visitedAt})`).orderBy(sql`date_trunc('day', ${visitEvents.visitedAt})`);
    return {
      periodDays: days,
      totalVisits: Number(totals?.total || 0),
      uniqueIps: Number(totals?.uniqueIps || 0),
      suspiciousEvents: Number(alerts?.total || 0),
      countries: countries.map((row) => ({ country: row.country, visits: Number(row.visits) })),
      topPaths: paths.map((row) => ({ path: row.path, visits: Number(row.visits) })),
      topIps: ips.map((row) => ({ ipAddress: row.ipAddress, country: row.country, visits: Number(row.visits), suspicious: Number(row.suspicious || 0) })),
      daily: daily.map((row) => ({ day: row.day, visits: Number(row.visits) })),
    };
  }),

  events: adminProcedure
    .input(z.object({
      days: z.number().int().min(1).max(365).default(30),
      country: z.string().trim().regex(/^[A-Z]{2}$/).optional(),
      page: z.number().int().min(1).max(10000).default(1),
      pageSize: z.number().int().min(10).max(100).default(25),
    }))
    .query(async ({ input }) => {
      const db = getDb();
      const since = new Date(Date.now() - input.days * 24 * 60 * 60 * 1000);
      const filters = input.country
        ? and(gte(visitEvents.visitedAt, since), eq(visitEvents.country, input.country))
        : gte(visitEvents.visitedAt, since);
      const offset = (input.page - 1) * input.pageSize;
      const [countRow] = await db.select({ total: sql<number>`count(*)` }).from(visitEvents).where(filters);
      const rows = await db.select({
        id: visitEvents.id,
        ipAddress: visitEvents.ipAddress,
        country: visitEvents.country,
        path: visitEvents.path,
        referrerHost: visitEvents.referrerHost,
        userAgent: visitEvents.userAgent,
        suspicious: visitEvents.isSuspicious,
        visitedAt: visitEvents.visitedAt,
      }).from(visitEvents).where(filters).orderBy(desc(visitEvents.visitedAt)).limit(input.pageSize).offset(offset);
      const total = Number(countRow?.total || 0);
      return {
        page: input.page,
        pageSize: input.pageSize,
        total,
        totalPages: Math.max(1, Math.ceil(total / input.pageSize)),
        events: rows,
      };
    }),
});
