import { z } from "zod";
import { desc, eq, sql } from "drizzle-orm";
import { createAdminRouter, adminProcedure } from "./admin-middleware";
import { getDb } from "../queries/connection";
import { adminChangeLogs, siteSettings } from "@db/schema";

const settingStateSchema = z.record(z.string(), z.string());

async function ensureChangeLogTable() {
  const db = getDb();
  await db.execute(sql`CREATE TABLE IF NOT EXISTS "admin_change_logs" ("id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "scope" varchar(100) NOT NULL, "entity_type" varchar(100) NOT NULL, "entity_id" varchar(100), "action" varchar(40) NOT NULL, "summary" varchar(255) NOT NULL, "before_state" jsonb, "after_state" jsonb, "created_at" timestamp NOT NULL DEFAULT now())`);
}

export const changeLogAdminRouter = createAdminRouter({
  list: adminProcedure
    .input(z.object({ limit: z.number().int().min(1).max(100).default(50) }).optional())
    .query(async ({ input }) => {
      await ensureChangeLogTable();
      const db = getDb();
      return db.select({
        id: adminChangeLogs.id,
        scope: adminChangeLogs.scope,
        entityType: adminChangeLogs.entityType,
        entityId: adminChangeLogs.entityId,
        action: adminChangeLogs.action,
        summary: adminChangeLogs.summary,
        beforeState: adminChangeLogs.beforeState,
        afterState: adminChangeLogs.afterState,
        createdAt: adminChangeLogs.createdAt,
      }).from(adminChangeLogs).orderBy(desc(adminChangeLogs.createdAt)).limit(input?.limit ?? 50);
    }),
  restore: adminProcedure
    .input(z.object({ id: z.number().int().positive() }))
    .mutation(async ({ input }) => {
      await ensureChangeLogTable();
      const db = getDb();
      const [entry] = await db.select().from(adminChangeLogs).where(eq(adminChangeLogs.id, input.id)).limit(1);
      if (!entry) throw new Error("Change history entry not found");
      if (entry.entityType !== "siteSettings" || !entry.beforeState) throw new Error("This change cannot be restored yet");
      const before = settingStateSchema.parse(entry.beforeState);
      const currentRows = await db.select({ key: siteSettings.key, value: siteSettings.value }).from(siteSettings);
      const current = Object.fromEntries(currentRows.map((row) => [row.key, row.value || ""]));
      for (const [key, value] of Object.entries(before)) {
        const existing = currentRows.find((row) => row.key === key);
        if (existing) await db.update(siteSettings).set({ value }).where(eq(siteSettings.key, key));
        else await db.insert(siteSettings).values({ key, value });
      }
      await db.insert(adminChangeLogs).values({
        scope: "site",
        entityType: "siteSettings",
        action: "restore",
        summary: `Restored site settings from change #${entry.id}`,
        beforeState: current,
        afterState: before,
      });
      return { success: true };
    }),
});

export async function snapshotSiteSettings() {
  await ensureChangeLogTable();
  const db = getDb();
  const rows = await db.select({ key: siteSettings.key, value: siteSettings.value }).from(siteSettings);
  return Object.fromEntries(rows.filter((row) => !["aiProvider", "aiApiKey", "aiApiUrl", "aiModel"].includes(row.key)).map((row) => [row.key, row.value || ""]));
}

export async function recordSiteSettingsChange(beforeState: Record<string, string>, afterState: Record<string, string>, summary: string) {
  await ensureChangeLogTable();
  const db = getDb();
  await db.insert(adminChangeLogs).values({
    scope: "site",
    entityType: "siteSettings",
    action: "update",
    summary,
    beforeState,
    afterState,
  });
}
