import { z } from "zod";
import { desc, eq, sql } from "drizzle-orm";
import { createAdminRouter, adminProcedure } from "./admin-middleware";
import { getDb } from "../queries/connection";
import { adminChangeLogs, siteSettings, projects, skills } from "@db/schema";

const settingStateSchema = z.record(z.string(), z.string());

async function ensureChangeLogTable() {
  const db = getDb();
  await db.execute(sql`CREATE TABLE IF NOT EXISTS "admin_change_logs" ("id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "scope" varchar(100) NOT NULL, "entity_type" varchar(100) NOT NULL, "entity_id" varchar(100), "action" varchar(40) NOT NULL, "summary" varchar(255) NOT NULL, "before_state" jsonb, "after_state" jsonb, "created_at" timestamp NOT NULL DEFAULT now())`);
}

export const changeLogAdminRouter = createAdminRouter({
  list: adminProcedure
    .input(z.object({ limit: z.number().int().min(1).max(100).default(50) }).optional())
    .query(async ({ input }) => {
      await ensureChangeLogTable();
      const db = getDb();
      return db.select({
        id: adminChangeLogs.id,
        scope: adminChangeLogs.scope,
        entityType: adminChangeLogs.entityType,
        entityId: adminChangeLogs.entityId,
        action: adminChangeLogs.action,
        summary: adminChangeLogs.summary,
        beforeState: adminChangeLogs.beforeState,
        afterState: adminChangeLogs.afterState,
        createdAt: adminChangeLogs.createdAt,
      }).from(adminChangeLogs).orderBy(desc(adminChangeLogs.createdAt)).limit(input?.limit ?? 50);
    }),
  restore: adminProcedure
    .input(z.object({ id: z.number().int().positive() }))
    .mutation(async ({ input }) => {
      await ensureChangeLogTable();
      const db = getDb();
      const [entry] = await db.select().from(adminChangeLogs).where(eq(adminChangeLogs.id, input.id)).limit(1);
      if (!entry) throw new Error("Change history entry not found");
      if (entry.entityType === "project" || entry.entityType === "skill") {
        const before = entry.beforeState as Record<string, unknown> | Array<Record<string, unknown>> | null;
        const after = entry.afterState as Record<string, unknown> | Array<Record<string, unknown>> | null;
        const table = entry.entityType === "project" ? projects : skills;
        const target = (after && !Array.isArray(after) ? after : before && !Array.isArray(before) ? before : null) as { id?: number } | null;
        if (Array.isArray(before) || Array.isArray(after)) {
          const rows = (before || []) as Array<{ id: number; orderIndex: number }>;
          for (const row of rows) await db.update(table).set({ orderIndex: row.orderIndex, updatedAt: new Date() }).where(eq(table.id, row.id));
        } else if (before) {
          const row = before as Record<string, unknown>;
          if (target?.id) await db.update(table).set({ ...row, id: undefined, updatedAt: new Date() } as never).where(eq(table.id, target.id));
          else await db.insert(table).values(row as never);
        } else if (target?.id) {
          await db.delete(table).where(eq(table.id, target.id));
        }
        await db.insert(adminChangeLogs).values({ scope: entry.scope, entityType: entry.entityType, entityId: entry.entityId, action: "restore", summary: `Restored ${entry.entityType} from change #${entry.id}`, beforeState: entry.afterState, afterState: entry.beforeState });
        return { success: true };
      }
      if (entry.entityType !== "siteSettings" || !entry.beforeState) throw new Error("This change cannot be restored yet");
      const before = settingStateSchema.parse(entry.beforeState);
      const currentRows = await db.select({ key: siteSettings.key, value: siteSettings.value }).from(siteSettings);
      const current = Object.fromEntries(currentRows.map((row) => [row.key, row.value || ""]));
      for (const [key, value] of Object.entries(before)) {
        const existing = currentRows.find((row) => row.key === key);
        if (existing) await db.update(siteSettings).set({ value }).where(eq(siteSettings.key, key));
        else await db.insert(siteSettings).values({ key, value });
      }
      await db.insert(adminChangeLogs).values({
        scope: "site",
        entityType: "siteSettings",
        action: "restore",
        summary: `Restored site settings from change #${entry.id}`,
        beforeState: current,
        afterState: before,
      });
      return { success: true };
    }),
});

export async function snapshotSiteSettings() {
  await ensureChangeLogTable();
  const db = getDb();
  const rows = await db.select({ key: siteSettings.key, value: siteSettings.value }).from(siteSettings);
  return Object.fromEntries(rows.filter((row) => !["aiProvider", "aiApiKey", "aiApiUrl", "aiModel"].includes(row.key)).map((row) => [row.key, row.value || ""]));
}

export async function recordEntityChange(entityType: "project" | "skill", entityId: number | null, action: string, beforeState: unknown, afterState: unknown, summary: string) {
  await ensureChangeLogTable();
  const db = getDb();
  await db.insert(adminChangeLogs).values({ scope: entityType, entityType, entityId: entityId === null ? null : String(entityId), action, summary, beforeState, afterState });
}

export async function snapshotProject(id: number) {
  const db = getDb();
  const [row] = await db.select().from(projects).where(eq(projects.id, id)).limit(1);
  return row || null;
}

export async function snapshotSkill(id: number) {
  const db = getDb();
  const [row] = await db.select().from(skills).where(eq(skills.id, id)).limit(1);
  return row || null;
}

export async function recordSiteSettingsChange(beforeState: Record<string, string>, afterState: Record<string, string>, summary: string) {
  await ensureChangeLogTable();
  const db = getDb();
  await db.insert(adminChangeLogs).values({
    scope: "site",
    entityType: "siteSettings",
    action: "update",
    summary,
    beforeState,
    afterState,
  });
}
